# Generated by Django 2.0 on 2018-01-09 19:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_auto_20171229_0955'),
        ('topics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fb_id', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
                ('image', models.CharField(max_length=500)),
                ('type', models.CharField(choices=[('page', 'Page of Facebook'), ('group', 'group')], default='page', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Relation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='topics.Entity')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.Profile')),
            ],
        ),
        migrations.RemoveField(
            model_name='like',
            name='page',
        ),
        migrations.RemoveField(
            model_name='like',
            name='profile',
        ),
        migrations.DeleteModel(
            name='Like',
        ),
        migrations.DeleteModel(
            name='Page',
        ),
    ]
