# Generated by Django 2.0 on 2018-01-11 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0002_auto_20180109_1959'),
    ]

    operations = [
        migrations.AddField(
            model_name='entity',
            name='fans',
            field=models.IntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='entity',
            name='type',
            field=models.CharField(choices=[('page', 'Page of Facebook'), ('group', 'Group of Facebook')], default='page', max_length=10),
        ),
    ]
