# Generated by Django 2.0 on 2018-01-18 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reaction',
            name='count',
            field=models.IntegerField(default=0),
        ),
    ]
