# Generated by Django 2.0 on 2018-01-18 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0002_reaction_count'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='image',
            new_name='fb_id',
        ),
        migrations.AddField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='comment',
            name='message',
            field=models.CharField(max_length=5000),
        ),
    ]
