# Generated by Django 2.0 on 2018-01-18 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0004_comment_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entity',
            name='image',
            field=models.CharField(default=None, max_length=1000),
        ),
    ]
