# Generated by Django 2.0 on 2018-01-18 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0005_auto_20180118_1223'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attachment',
            name='type',
        ),
        migrations.RemoveField(
            model_name='attachment',
            name='url',
        ),
        migrations.RemoveField(
            model_name='storie',
            name='likes',
        ),
        migrations.AddField(
            model_name='attachment',
            name='message',
            field=models.CharField(default=None, max_length=5000),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='description',
            field=models.CharField(default=None, max_length=5000),
        ),
    ]
