# Generated by Django 2.0 on 2018-01-18 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0007_auto_20180118_1319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='description',
            field=models.CharField(default=None, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='message',
            field=models.CharField(default=None, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='image',
            field=models.CharField(default=None, max_length=1000, null=True),
        ),
    ]
