# Generated by Django 2.0 on 2018-01-18 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0009_auto_20180118_1330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='title',
            field=models.CharField(default=None, max_length=500, null=True),
        ),
    ]
