# Generated by Django 2.0 on 2018-01-19 03:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0010_auto_20180118_1354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storie',
            name='entity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='stories.Entity'),
        ),
    ]
