# Generated by Django 2.0 on 2018-02-16 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0011_auto_20180119_0330'),
    ]

    operations = [
        migrations.AddField(
            model_name='storie',
            name='sentiment',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
