# Generated by Django 2.0 on 2018-02-16 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0013_auto_20180216_1013'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='sentiment',
            field=models.DecimalField(decimal_places=15, default=0, max_digits=30),
        ),
    ]
